### ISSUE TITLE
Won't work with recent Fabric versions

### ISSUE THREAD

**Issue by Suitov** [adriantodt/Winged#11]
I'd like to update my game to the latest Fabric, because I use other mods that require a later version than I'm using. However, Winged causes crashes (confirmed with Not Enough Crashes) with Fabric versions after (about?) Fabric 0.24.0. Logs on request.

Would it be possible to update, please? I wish you good luck that it's as simple as incrementing the version number...

**Comment by GabrielOlvH** [comment]
logs please

**Comment by Suitov** [comment]
Here we go.

And, this is very random, this crash in particular is anticipated by the Mojang logo being invisible on the loading screen, so it's just a red space instead.

`---- Minecraft Crash Report ----
// There are four lights!

Time: 2021-01-18 20:27:43 GMT
Description: Unexpected error

java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at java.util.TimSort.mergeLo(Unknown Source)
    at java.util.TimSort.mergeAt(Unknown Source)
    at java.util.TimSort.mergeCollapse(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at java.util.ArrayList.sort(Unknown Source)
    at java.util.Collections.sort(Unknown Source)
    at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:50)
    at draylar.identity.IdentityClient.lambda$onInitializeClient$0(IdentityClient.java:44)
    at net.minecraft.client.MinecraftClient.handler$zmf000$onStartTick(MinecraftClient:6381)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_746['Suitov'/2690, l='ClientLevel', x=29.50, y=63.00, z=-96.67]]
  Chunk stats: SodiumChunkCache: 269
  Level dimension: minecraft:overworld
  Level spawn location: World: (-80,64,-103), Chunk: (at 0,4,9 in -5,-7; contains blocks -80,0,-112 to -65,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 25847746 game time, 26790292 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 673430728 bytes (642 MB) / 1412956160 bytes (1347 MB) up to 1908932608 bytes (1820 MB)
  CPUs: 4
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
  Suspected Mods: Fabric Loader (fabricloader), Identity (identity)
  Fabric Mods: angerable-patch: Angerable Patch 1.0.0-1.16.1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               betterthanmending: BetterThanMending 1.2.0
               cardinal-components-base: Cardinal Components API (base) 2.7.5
               cardinal-components-entity: Cardinal Components API (entities) 2.7.5
               carrier: Carrier 1.6.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.3
               couplings: Couplings 1.3.3
               dynamicfps: Dynamic FPS 1.2.1
               easierenchanting: Easier Enchanting 1.4.0
               enchantablehorsearmor: Enchantable Horse Armor 1.0a
               fabric: Fabric API 0.24.0+build.411-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
               fabricloader: Fabric Loader 0.10.3+build.211
               fallflyinglib: FallFlyingLib 1.1.0
               fastfurnace: FastFurnace 2.3
               flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
               gottaclimbfast: Gotta Climb Fast! 1.0
               harvest: Harvest 1.2.12
               horsestatsvanilla: Horse Stats Vanilla 2.0.1
               iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
               identity: Identity 1.10.2-beta-1.16.3
               infinityfix: Infinity Fix 1.1.0
               instantlava: InstantLava 1.2.0
               io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.1
               irishwolves: Irish Wolves 1.0.0
               leadvillagers: Lead Villagers 2.1.0+mc1.16.1
               leafmealone: Leaf Me Alone 2.1
               libblockattributes_core: LibBlockAttributes (Core) 0.7.0
               libblockattributes_items: LibBlockAttributes (Items) 0.7.0
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               minecraft: Minecraft 1.16.4
               missingbits: Missing Bits v1.16.3 Fabric b1
               mo_glass: Mo Glass 1.5-MC1.16.4
               modmenu: Mod Menu 1.14.13+build.19
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               phosphor: Phosphor 0.7.0+build.10
               playerabilitylib: Pal 1.2.1
               portaltags: Portal Tags 2.1.0
               respawnablepets: Respawnable Pets 1.16.4-1
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               simpledrawers: Simple Drawers 1.8.0-1.16.3
               sodium: Sodium 0.1.0
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               stockpile: Stockpile 1.1.5+1.16.1
               strongandfairanvils: Strong and Fair Anvils 0.3.0+1.16
               winged: Winged Mod 1.16.2-1.4.1
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               xaerominimap: Xaero's Minimap 20.28.2
               xaeroworldmap: Xaero's World Map 1.11.4
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 760/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fast
  Resource Packs: vanilla, fabric/autoconfig1u, fabric/cloth-config2, fabric/easierenchanting, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-language-kotlin, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/fallflyinglib, fabric/flora-doubling, fabric/gottaclimbfast, fabric/harvest, fabric/horsestatsvanilla, fabric/infinityfix, fabric/instantlava, fabric/irishwolves, fabric/leadvillagers, fabric/mo_glass, fabric/phosphor, fabric/playerabilitylib, fabric/portaltags, fabric/respawnablepets, fabric/roughlyenoughitems, fabric/roughlyenoughitems-runtime, fabric/simpledrawers, fabric/staticdata, fabric/strongandfairanvils, fabric/winged, fabric/wolveswitharmor, fabric/xaeroworldmap, fabric/dynamicfps, fabric/notenoughcrashes, fabric/sodium, fabric/missingbits, fabric/xaerominimap, file/VanillaTweaks_aesthetic_r506394.zip, file/VanillaTweaks_crafting_c403931.zip, fabric/fastfurnace, fabric/iamverysmart, fabric/leafmealone, fabric/lithium, fabric/modmenu, fabric/carrier, fabric/couplings, fabric/identity, fabric/libblockattributes_core, fabric/libblockattributes_items, fabric/stockpile (incompatible)
  Current Language: English (United Kingdom)
  CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0`

**Comment by GabrielOlvH** [comment]
Update the Identity mod

**Comment by GabrielOlvH** [comment]
Winged isn't even loaded in the crash report you sent.

**Comment by Suitov** [comment]
I can't updated the Identity mod, as I can't update Fabric, because when I try to update Fabric my game fails to load with the above log. Are there known conflicts with Identity?

Winged was activated in the log I sent - that was the output when I tried to load the game. REC screen said Winged was the cause of the crash.

I've tried updating Fabric and all other mods while having Winged deactivated, and stuff seems to be loading fine, so it def seems like a Winged conflict somewhere.

**Comment by Suitov** [comment]
Ah, this is so weird. Sorry for multiple updates.

Sooo... deactivated Winged, updated Fabric and other mods. Launched game and confirmed working.
Reactivated Winged.
Game... still loaded and seems to be working still.

**Comment by GabrielOlvH** [comment]
Winged works just fine in newer versions. Your crash was because you had an outdated version of Identity with a newer version of Fabric API
