### ISSUE TITLE
Crash within REI on AOF4

### ISSUE THREAD

**Issue by Azercoco** [adriantodt/Winged#34]
I was playing AOF4 0.0.7 and I encounterd a crash when browsing the recipes in REI. Here is the crash report :

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/20/21, 11:25 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index 7 out of bounds for length 7
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.adriantodt.winged.integration.rei.WingRecipeCategory.setupDisplay(WingRecipeCategory.java:57)
	at net.adriantodt.winged.integration.rei.WingRecipeCategory.setupDisplay(WingRecipeCategory.java:25)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25426(DefaultDisplayViewingScreen.java:248)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.lambda$init$9(DefaultDisplayViewingScreen.java:221)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.onClick(ButtonWidget.java:237)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25401(DefaultDisplayViewingScreen.java:461)
	at net.minecraft.class_312.method_1598(class_312.java:128)
	at net.minecraft.class_312.method_22687(class_312.java:166)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22685(class_312.java:166)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.adriantodt.winged.integration.rei.WingRecipeCategory.setupDisplay(WingRecipeCategory.java:57)
	at net.adriantodt.winged.integration.rei.WingRecipeCategory.setupDisplay(WingRecipeCategory.java:25)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25426(DefaultDisplayViewingScreen.java:248)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.lambda$init$9(DefaultDisplayViewingScreen.java:221)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.onClick(ButtonWidget.java:237)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25401(DefaultDisplayViewingScreen.java:461)
	at net.minecraft.class_312.method_1598(class_312.java:128)
	at net.minecraft.class_312.method_22687(class_312.java:166)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22685(class_312.java:166)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cnd000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['Azercoco'/302, l='ClientLevel', x=64.92, y=84.57, z=234.80]]
	Chunk stats: 841, 596
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,74,112), Section: (at 0,10,0 in 4,4,7; chunk contains blocks 64,0,112 to 79,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18057 game time, 18057 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, charmonium/journeyman, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 600264296 bytes (572 MiB) / 4194304000 bytes (4000 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f91
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25519.24
	Virtual memory used (MB): 21156.58
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 665.13
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4000m -Xmx8192m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.1.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		ambientenvironment: Ambient Environment fabric-1.17-rc2-6.0.0.11
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.2.21
		artifality: Artifality 0.3.3
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.2
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balm-fabric: Balm 1.2.0+0
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		basicaiots: Basic AIOTs 1.3.1
		bclib: BCLib 0.2.4
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		betterend: Better End 0.10.5-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		biome_locator: Biome Locator 1.1.3
		blast: BLAST 1.7
		blockus: Blockus 2.2.7+1.17.1
		blue_endless_jankson: jankson 1.2.1
		breakprogress: Break Progress 1.0.1
		builtinservers: Builtin Servers 1.0.1-BETA+1.17
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17-7.0.0.2
		coat: Coat 1.0.0-beta.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.5
		controlling: Controlling For Fabric 1.1.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftingtweaks: Crafting Tweaks 13.0.0+0
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		crusade: Crusade 1.2.4
		dankstorage: Dank Storage 2.0a-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.5
		darkpaintings: Dark Paintings 3.0.6
		dawn: Dawn API 2.0.3
		de_javagl_obj: obj 0.3.0
		deathlog: DeathLog 0.1.3
		defaultsettings: DefaultSettings 3.0.3
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.2-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.2-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.2-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.2-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.2-beta
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.4
		ecotones: Ecotones 0.8.0
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchantmentdescriptions: Enchantment Descriptions 3.0.12
		entitybanners: Entity Banners 1.0.1-BETA+1.17
		expandedstorage: Expanded Storage 7.0.0-alpha.33
		extragenerators: Extra Generators 1.0.6-BETA+1.17
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+b246072f13
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.0-pre.04+648b8b6c18
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.21
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.9
		glassential: Glassential 1.17-1.2.0
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		goml: Get Off My Lawn 1.4.0-beta
		harvest_scythes: Harvest Scythes 2.0.5
		hologram-api: Hologram API 0.1.2+1.17.1
		horseinfo: Horse Info 0.3.0-1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		impaled: Impaled 1.0.1
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1
		indrev: Industrial Revolution 1.10.0-alpha.10
		inmis: Inmis 2.3.1-1.17
		inventorysorter: Inventory Sorter 1.7.9-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.8-BETA+1.17
		kjsextras: KubeJS Extras 1.3.2
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lifts: Lifts 1.2-BETA+1.17
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.3
		lovely_snails: Lovely Snails 1.0.2+1.17
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.0.3
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-extra-generators: megane-extra-generators 5.1.1+1.0.5-BETA-1.17
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.1+0.4.2
		megane-industrial-revolution: megane-industrial-revolution 5.1.1+1.10.0-alpha.4
		megane-kibe: megane-kibe 5.1.1+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.1+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.1.1+0.5.2-alpha.02
		megane-runtime: megane-runtime 5.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.1+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.1.1+1.1.1
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.2
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modern_industrialization: Modern Industrialization 0.5.3
		modmenu: Mod Menu 2.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		myron: Myron 1.6.0
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.1.0
		notes: Notes 1.0.6
		nyfsquivers: Nyf's Quivers Fabric-0.2.4
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_tukaani_xz: xz 1.8
		outvoted: Outvoted 2.0.0-alpha.8
		owo: OwO 0.1.1
		packages: Packages 1.2.1
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		placeholder-api: Fabric Placeholder API 1.0.1+1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		pling: Pling 1.4.0
		polymer: Polymer 0.1.0-pre9+1.17.1
		promenade: Promenade 2.1.2
		quickshulker: Quick Shulker 1.1.17-1.17
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.3-beta+build.55
		redbits: Red Bits 1.9.0
		repurposed_structures: Repurposed Structures 2.1.1+1.17.1
		respawnablepets: Respawnable Pets 1.17-2
		rhino: Rhino 1605.1.1-build.23
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 2.0.5
		secretrooms: Secret Rooms 1.0.0+1.17
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc3-1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		shulkerutils: shulkerutils 1.0.1-1.17
		simple-rpc: Simple Rpc 1.17-2.2.2-fabric
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		slotlock: SlotLock 1.0.4-BETA+1.17
		smootherbedrock: Smoother Bedrock 1.0.1
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.2.0+1.17
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.7
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		survivalisland: Survival Island 0.1.5
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.3-beta+build.55
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		textile_backup: Textile Backup 2.1.0-1.17
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.3-1.16
		totemmod: Wither Totems Mod 0.3.2
		trident_return: TridentReturn 1.2.4
		trinkets: Trinkets 3.0.2
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		universal-graves: Universal Graves 1.0.7+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagershats: Goosik's Villager Hats 1.2.0
		waystones: Waystones 2.0.2
		winged: Winged Mod 1.17-3.0.0-beta.2
		wirelessnetworks: Wireless Networks 1.1.2
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		woods_and_mires: Woods and Mires 1.1.0+1.17
		workings: Workings 1.0.7
		wthit: wthit 3.7.0
		xaerominimap: Xaero's Minimap 21.13.0
		xaeroworldmap: Xaero's World Map 1.14.6.1
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman, charmonium/journeyman
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Player Count: 1 / 8; [class_3222['Azercoco'/302, l='ServerLevel[Test]', x=64.92, y=84.57, z=234.80]]
	Data Packs: vanilla, secretrooms:server_pack, Fabric Mods
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\coren\Desktop\Jeu\MultiMC\instances\All-of-Fabric-4-0.0.7\minecraft\crash-reports\crash-2021-07-20_11.25.28-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

```

**Comment by GabrielOlvH** [comment]
Thanks for reporting, this is fixed as of 3.0.0 which will be available on CurseForge shortly.
